In [7]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [9]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [11]:
percentage = 100*A/(cal.reshape(1,4))
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


A is a 3 x 4 matrix and cal is a 1 x 4 matrix. 
Basically, (m,n) */+- (1,n) or (m,1) or R it repeats the values to do the operation element wise.

In [14]:
def colvec(rowvec):
    v = np.asarray(rowvec)
    return v.reshape(v.size,1)

a = [1, 2, 1, 3, 1]
print(colvec(a) + a)


[[2 3 2 4 2]
 [3 4 3 5 3]
 [2 3 2 4 2]
 [4 5 4 6 4]
 [2 3 2 4 2]]


In [16]:
a = np.random.randn(5)
print(a.shape)
print(a)


a = np.random.randn(5,1)
print(a.shape)
print(a)

(5,)
[-0.51428008 -1.19133752  0.55590098 -1.31109222  1.41508085]
(5, 1)
[[-0.10759852]
 [-0.25027267]
 [ 0.00381987]
 [-0.01843194]
 [-0.56820057]]


Try not to use the (5,) (rank 1 arrays) data structure. It doesnt behave like a row vector

In [17]:
assert(a.shape == (5,1))

In [19]:
a = np.random.randn(5)
print(a.reshape((5,1)))
print(a)

[[ 1.46201716]
 [-0.4380928 ]
 [ 1.27003317]
 [-1.88656419]
 [ 0.85026162]]
[ 1.46201716 -0.4380928   1.27003317 -1.88656419  0.85026162]
